import { createLocalRepository } from "../utils/localRepository"

const SEED = [
  {
    id: 1,
    name: "Publikasi",
    slug: "/publikasi",
    banner: "/images/banner-publikasi.png",
    categories: ["Daily Economic", "bjb Business Insight", "Lainnya"],
    gridCategories: ["Daily Economic"],
    layout: "default",
    gallery: [],
  },
  {
    id: 2,
    name: "Makro Ekonomi",
    slug: "/makroekonomi",
    banner: "",
    categories: ["Makro Brief", "Ekonomi Makro"],
    gridCategories: ["Makro Brief", "Ekonomi Makro"],
    layout: "default",
    gallery: [],
  },
  {
    id: 3,
    name: "Industri",
    slug: "/industry",
    banner: "",
    categories: ["Positioning", "Market Share", "Rasio Industri", "Kajian NPL"],
    gridCategories: ["Positioning", "Market Share", "Rasio Industri", "Kajian NPL"],
    layout: "default",
    gallery: [],
  },
  {
    id: 4,
    name: "Regional",
    slug: "/regional",
    banner: "",
    categories: ["Mapping Ekonomi", "Pemetaan Sektoral Ekonomi & Kredit Perbankan"],
    gridCategories: [],
    layout: "regional",
    gallery: [],
  },
  {
    id: 5,
    name: "Daily Market Dashboard",
    slug: "/daily-market-dashboard",
    banner: "",
    categories: ["Daily Market"],
    gridCategories: ["Daily Market"],
    layout: "default",
    gallery: [],
  },
  {
    id: 6,
    name: "Outlook Economic Forum",
    slug: "/outlook-economic-forum",
    banner: "",
    categories: ["Pembicara 1", "Pembicara 2", "Pembicara 3"],
    gridCategories: [],
    layout: "forum",
    gallery: [],
  },
  {
    id: 7,
    name: "Market Intelligence",
    slug: "/market-intelligence",
    banner: "",
    categories: ["Market Intelligence"],
    gridCategories: ["Market Intelligence"],
    layout: "default",
    gallery: [],
  },
]

const repo = createLocalRepository("mroe:pages", SEED)

export const pageService = {
  getAll: repo.getAll,
  getById: repo.getById,
  create: repo.create,
  update: repo.update,
  remove: repo.remove,
  reset: repo.reset,
}
